"""1ra parte

Revision ID: 0d443ae89a1a
Revises: 
Create Date: 2024-09-24 20:29:07.839714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d443ae89a1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('victorias', sa.Integer(), nullable=False),
    sa.Column('empates', sa.Integer(), nullable=False),
    sa.Column('derrotas', sa.Integer(), nullable=False),
    sa.Column('goles_f', sa.Integer(), nullable=False),
    sa.Column('goles_c', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local', sa.Integer(), nullable=False),
    sa.Column('visitante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['local'], ['seleccion.id'], ),
    sa.ForeignKeyConstraint(['visitante'], ['seleccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partidos')
    op.drop_table('seleccion')
    # ### end Alembic commands ###
