"""Agregado fecha

Revision ID: 1d83d945cbb4
Revises: a647a152c910
Create Date: 2024-09-25 23:50:05.183338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d83d945cbb4'
down_revision = 'a647a152c910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
