"""Columna añadida

Revision ID: eb67c8f426a4
Revises: 
Create Date: 2024-09-19 00:30:18.891586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb67c8f426a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partidos')
    op.drop_table('seleccion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seleccion',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('victorias', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('empates', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('derrotas', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('goles_f', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('goles_c', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('partidos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('local', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('visitante', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
