"""Tablas creadas

Revision ID: feaaab5f3ffe
Revises: eb67c8f426a4
Create Date: 2024-09-19 00:34:37.939583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feaaab5f3ffe'
down_revision = 'eb67c8f426a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('victorias', sa.Integer(), nullable=False),
    sa.Column('empates', sa.Integer(), nullable=False),
    sa.Column('derrotas', sa.Integer(), nullable=False),
    sa.Column('goles_f', sa.Integer(), nullable=False),
    sa.Column('goles_c', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local', sa.Integer(), nullable=False),
    sa.Column('visitante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['local'], ['seleccion.id'], ),
    sa.ForeignKeyConstraint(['visitante'], ['seleccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partidos')
    op.drop_table('seleccion')
    # ### end Alembic commands ###
